# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets: ~
    profiler:
        collect: false

when@test:
    parameters:
        log.handler: 'stderr'
        log.level: 'error'
        satis_filename: "vfs://root/satis.json"
        satis_log_path: "vfs://root/satis/"
        admin.auth: false
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        profiler:
            collect: false

when@testsecure:
    parameters:
      admin.auth: true
      admin.users:
        test:
          password: test
          roles: 'ROLE_ADMIN'
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        profiler:
            collect: false