imports:
  - { resource: defaults.yml }
  - { resource: parameters.yml }
  - { resource: security.yml }

parameters:
  container.autowiring.strict_mode: true

framework:
  secret: "%secret%"
  session:
    save_path: '%kernel.project_dir%/var/sessions'
  assets: ~
  profiler:
    collect: false
  lock:
    resources:
      satis: "flock"
      build: "flock"

twig:
  form_themes: ['bootstrap_3_layout.html.twig']
  globals:
    satis: '@Playbloom\Satisfy\Model\Configuration'

monolog:
  handlers:
    errors:
      type: fingers_crossed
      action_level: '%log.level%'
      handler: '%log.handler%'
      bubble: false
    file_log:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      max_files: 30
    stderr:
      type: stream
      path: "php://stderr"
