parameters:
  log.handler: 'file_log'
  log.level: 'error'
  github.secret: '%env(GITHUB_SECRET)%'
  github.source_urls: [ 'git_url', 'ssh_url', 'clone_url', 'svn_url' ]
  github.auto_add_repo: false
  github.auto_add_repo_type: false
  gitlab.secret: '%env(GITLAB_SECRET)%'
  gitlab.auto_add_repo: false
  gitlab.auto_add_repo_type: ~
  gitlab.prefer_ssh_url_type: false
  gitea.secret: '%env(GITEA_SECRET)%'
  gitea.source_urls: [ 'git_url', 'ssh_url', 'clone_url', 'svn_url' ]
  gitea.auto_add_repo: false
  gitea.auto_add_repo_type: false
  devops.secret: '%env(DEVOPS_SECRET)%'
